getodk/web-forms

.github/workflows/ci.yml, packages/xforms-engine/src/lib/reactivity/createSelectItems.ts, packages/xforms-engine/test/lib/reactivity/createSelectItems.test.ts
Fixes #83.
Supersedes and closes #102 as well. Differences from that PR:
- Breaks the fixes for these (related, but) distinct bugs into separate commits:
- Translated _dynamic select itemset labels_ (e.g. `<select1><itemset nodeset="instance('choices')/root/item"><label ref="jr:itext(itextId)"/>…`) are not client-reactive.
- Translated labels of _static select items_ (e.g. `<select><item><label ref="jr:itext('foo')"/>…`) are **also** not client-reactive.
The distinction is discussed in #83. I expect having separate commits could be helpful in the future, whenever we need to reason about the slight differences in how each case flows through the engine's reactive internals.
- Adds tests for both bugs, exercising reactivity of these scenarios:
- Trigger an effect on load, reflecting initial …
=> Fix: client reactivity of translated select item labels

.changeset/neat-spoons-pull.md, packages/scenario/test/form-definition-validity.test.ts, packages/scenario/test/relevant.test.ts, packages/scenario/test/repeat-relevant.test.ts, packages/scenario/test/repeat.test.ts, packages/scenario/test/smoketests/child-vaccination.test.ts, packages/xforms-engine/src/instance/Group.ts, packages/xforms-engine/src/instance/RepeatInstance.ts, packages/xforms-engine/src/instance/RepeatRange.ts, packages/xforms-engine/src/instance/Root.ts, packages/xforms-engine/src/instance/SelectField.ts, packages/xforms-engine/src/instance/StringField.ts, packages/xforms-engine/src/instance/Subtree.ts, packages/xforms-engine/src/instance/abstract/DescendantNode.ts, packages/xforms-engine/src/instance/abstract/InstanceNode.ts, packages/xforms-engine/src/instance/index.ts, packages/xforms-engine/src/instance/internal-api/EvaluationContext.ts, packages/xforms-engine/src/instance/internal-api/ValueContext.ts, packages/xforms-engine/src/lib/reactivity/createChildrenState.ts, packages/xforms-engine/src/lib/reactivity/createComputedExpression.ts, packages/xforms-engine/src/lib/reactivity/createSelectItems.ts, packages/xforms-engine/src/lib/reactivity/createValueState.ts, packages/xforms-engine/src/lib/reactivity/materializeCurrentStateChildren.ts, packages/xforms-engine/test/instance/Root.test.ts, packages/xforms-engine/test/instance/instance.test.ts
This PR includes a handful of fixes and improvements addressing issues found in #110, generally with a common repeat-related theme.
The commit notes go into some detail of each fix. I'll highlight some high level details here as well.
1. ad607dc Fix `InconsistentChildrenStateError` cases that currently affect `scenario`. This fix shouldn't affect the `web-forms` Vue UI client (as it only affects clients using Solid), but it was important to fix first so that the other fixes won't be obscured by introducing this same error.
2. 0212b9f Fix a variety of issues where behavior is correct for the first repeat instance in a range (or within that repeat instance, or referencing into it) but incorrect for subsequent repeat instances. The change doesn't address **all** such cases, but it is …
=> Several repeat-related fixes

.changeset/swift-ducks-divide.md, packages/web-forms/build-preview/index.html, packages/web-forms/e2e/build/style.test.ts, packages/web-forms/e2e/vue.test.ts, packages/web-forms/package.json, packages/web-forms/playwright.config.ts, packages/web-forms/src/components/OdkWebForm.vue, packages/web-forms/src/index.ts, packages/web-forms/vite.config.ts, packages/web-forms/vitest.config.ts, yarn.lock
After decomposing styles from theme.scss into SFC in #113, build process started generated separate css file instead of generating just a single `index.js` file. Because styles defined in SFC file scan't be accessed in `index.ts` as we do for other style files, I ended up using a plugin that post-processes styles and adds them in index.js file as `IIFE` that adds `<style>` tags in the document head. If we prefer `document.adoptedStyleSheets` instead I can use `injectCodeFunction ` of the plugin.
=> fix: include css in the built js file

.changeset/pretty-walls-relate.md, packages/xforms-engine/src/lib/reactivity/validation/createAggregatedViolations.ts, packages/xforms-engine/test/lib/reactivity/createAggregatedViolations.test.ts
=> Fix: reactivity of aggregated validation violations on deep descendants

.gitattributes
=> Fix: updated gitattributes file

.changeset/wise-colts-thank.md, .github/PULL_REQUEST_TEMPLATE.md
This is roughly based on the templates from:
- getodk/central
- enketo/enketo
It specifically adds a browser checklist, as that discussion is what prompted us to add this.
- - -
Before we merge this, I would like to consider adding:
- A section to describe the PR's changes. This is something I'm trying to make an effort to do on at least non-trivial/non-obvious changes, and would like to encourage as it's really helpful to look back and find context for changes as they occur. This could be really basic, or could encourage specific kinds of details (e.g. things to look out for, things that were intentionally deferred, aspects of approach of particular interest/warranting particular scrutiny). If the latter, there may be overlap with the _best solution_ section.
- Either checkboxes for …
=> Add PR template

.changeset/quiet-donkeys-tie.md, packages/scenario/resources/smoketests/child_vaccination_VOL_tool_v12-alt.xml, packages/scenario/src/jr/event/PositionalEvent.ts, packages/scenario/src/jr/event/getPositionalEvents.ts, packages/scenario/test/repeat.test.ts, packages/scenario/test/smoketests/child-vaccination.test.ts, packages/scenario/test/xpath/functions/current.test.ts, packages/xforms-engine/src/instance/repeat/BaseRepeatRange.ts, packages/xforms-engine/src/instance/repeat/RepeatRangeControlled.ts
Addresses issue discussed in #205, updates other related "indefinite repeat" tests.
I'm not sure whether we should keep #205 open or not. I'll note that I did do the brief timeboxed investigation described near the end of that issue. The fix I had in mind did not work as described. It's possible there are adjustments to the approach which could make it work, but I think it's best to prioritize separately so we can get CI passing and move forward.
I doubt it's applicable, but I'll gladly check if there's any doubt.
The vast majority of the change is testing.
Regarding the `jr:count` evaluation context fix: it is definitely not the best possible solution! It is a solution consistent with how we've handled other presentation of the same problem. The better solution will come with #203 if we …
=> Fix: evaluate `jr:count` in context of affected repeat; fix/update child vaccination smoketest, other Scenario tests

.changeset/stale-actors-learn.md, packages/xforms-engine/src/instance/children.ts
Closes: NA
All tests pass. 
Tried previewing a Form with `upload`, it renders correctly 
NA
There's no regression risk.
http://xlsform-online.sadiqkhoja.com/downloads/acd96076c01a4facb65111b038b9adf64jj09j3z/PhilSA%20Disaster%20Incidence.xml
- Corrected the bodyElement type of `upload` node
=> Fix: name of upload node is upload not range

.changeset/mean-socks-repair.md, .changeset/nice-bags-sneeze.md, .changeset/stale-actors-learn.md, README.md, feature-matrix.json, packages/scenario/CHANGELOG.md, packages/scenario/package.json, packages/ui-solid/CHANGELOG.md, packages/ui-solid/package.json, packages/web-forms/CHANGELOG.md, packages/web-forms/package.json, packages/xforms-engine/CHANGELOG.md, packages/xforms-engine/package.json, scripts/feature-matrix/render.js, scripts/feature-matrix/template.mustache
- Ran `changeset version` command and updated description in changelog to removed `trigger` from Unsupported nodes
- Fixed feature matrix rendering, it had become quite ugly
- Updated feature matrix to mark `trigger` as WIP
Before:
After:
NA
I can move feature matrix rendering from this PR. I tried various things to fix alignment of the headings but nothing seems to work. I ended up added hard coded spacing between category heading and progress-bar (don't want to spend to much time here)
None
NA
=> Prepare release @getodk/web-forms 0.4.0

README.md, feature-matrix.json, scripts/feature-matrix/README.md
I noticed that XLSForm `trigger` was marked as in progress but that corresponds to XForms `setvalue` which is not yet in progress. ODK XForms `trigger` is exposed in XLSForm as `acknowledge`. I don't know the full history of this weirdness!
While I was there, I also noticed that we do have a full implementation of `likert` and that `table-list` is an XLSForm alias so doesn't need to be here.
I had some trouble figuring out how to run the script so I added a few more breadcrumbs. I also added a section header to try to improve the Github table of contents view.
This doesn't need a changeset because it's not end-user-facing.
=> Update the feature matrix

packages/web-forms/src/demo/HomePage.vue
I mentioned in Slack I want to consider some minimal snapshot testing with screenshots. But as I say under **what's changed**, I don't want to delay this fix for that. I also don't know exactly what making that effective would look like, and I'd want to flag a couple more points of reference (especially in the actual form view).
It's definitely not the best possible solution. But it's the most minimal change I could find.
It's possible I missed some nuance in how the affected styles are overridden at larger breakpoints, but I am pretty confident that I didn't.
N/A
Looking at the Web Forms Preview as deployed on getodk.org, on my phone I noticed:
1. Many of the blocks were significantly wider than the viewport. This is especially noticeable for the blocks in the “Try real forms” section, …
=> Fix: width overflow on mobile

.changeset/sweet-zebras-boil.md, .changeset/tame-panthers-fetch.md, packages/common/CHANGELOG.md, packages/common/package.json, packages/common/src/fixtures/REAMDE.md, packages/common/src/fixtures/test-web-forms/simple-dag-cycle.xml, packages/common/src/fixtures/test-web-forms/xpath-syntax-error.xml, packages/common/src/fixtures/test-web-forms/xpath-unknown-function.xml, packages/common/src/lib/runtime-types/shared-type-predicates.ts, packages/ui-solid/CHANGELOG.md, packages/ui-solid/package.json, packages/web-forms/CHANGELOG.md, packages/web-forms/package.json, packages/web-forms/src/components/Form/FormLoadFailureDialog.vue, packages/web-forms/src/components/OdkWebForm.vue, packages/web-forms/src/lib/error/FormInitializationError.ts, packages/web-forms/src/lib/error/FormLoadFailure.ts, packages/web-forms/tests/components/OdkWebForm.test.ts, packages/web-forms/tests/helpers.ts, packages/web-forms/tsconfig.vitest.json, packages/xforms-engine/package.json, packages/xpath/CHANGELOG.md, packages/xpath/package.json
A few tests. I think we'll want to expand testing in this area significantly, probably at different levels of the stack.
It's approximately the quickest solution, which was the priority for now. There are known areas for improvement, discussed under **What's changed** below.
If users previously depended on getting no information whatsoever when a form fails to load, this will break that workflow.
Added a few fixtures, each demonstrating a known failure case.
Here, a “form load failure” is any `Promise` rejection produced by the engine’s `initializeForm` entrypoint. This is intentionally broad, and what I think is a relatively minimal first pass that might be useful to users (and to us).
“Relatively” minimal because I took the opportunity to lay a bit of groundwork for a few things either …
=> Basic presentation of form load failures; prepare release: `@getodk/web-forms` 0.5.0

packages/common/src/fixtures/import-glob-helper.ts, packages/common/src/fixtures/xform-attachments.ts, packages/common/src/fixtures/xforms.ts, packages/web-forms/e2e/build/wf-preview.test.ts, packages/web-forms/src/components/OdkWebForm.vue, packages/web-forms/src/demo/DemoForm.vue
Added an e2e test which loads all of the Web Forms Preview form links, from the build product. That should be much more reliable than any manual testing I might do.
It would be preferable if specific fixtures could be referenced by something stable, and not rely on anything dynamic at build time.
It's possible some other nuance of glob loading is affected by this. But I would expect to see some sign of that either in `scenario` or dev mode, both of which still seem to be working as expected.
The links on the preview page should suffice.
- Restored use of build-time asset URLs in links to XForm fixtures
- Added an e2e test to ensure that doesn't break again, along with a couple of basic Vue template supports for (hopefully) clearer intent in e2e tests going forward
=> Fix: Web Forms Preview demo form links 

README.md
Otherwise someone has to open the yarn file to see that Volta is used
=> Add reference to Volta

.changeset/ten-experts-type.md, packages/xforms-engine/src/instance/resource.ts
I built a minimal test html file of the web-component build of web-forms and manually tested to make sure it works.
I had tried catching the error, but thought it best to prevent the error from happening at all.  The suggested change also preserve isomorphism and avoids dependency on any browser specific APIs.
This change shouldn't affect any users.
Will work with any form.
Basically just unpacked the fetchResource function (usually built-in fetch I think) before calling it.  When you try to call it on the object as options.fetchResource it throws an illegal invocation error.
I have only minimal experience with the web-forms code base, so I'd recommend double-checking with someone who has more experience.  I'm honestly a bit confused how this issue didn't come up earlier.  I wonder if it …
=> fix illegal invocation issue when fetching form xml

.changeset/friendly-monkeys-grab.md, .changeset/strange-needles-compare.md, packages/scenario/src/jr/Scenario.ts, packages/web-forms/src/components/OdkWebForm.vue, packages/web-forms/src/demo/FormPreview.vue, packages/xforms-engine/src/client/RootNode.ts
Supersedes and closes #289. Closes #23. Closes #290.
It would shock me if there's anything browser-specific here.
Types do much of the work. Added console logs in `FormPreview.vue` demonstrate both handlers working.
I mentioned this in Slack, and will reiterate here: in hindsight, since there are two distinct `SubmissionResult` payload formats, events may not be the best API for this. On the other hand, it may be possible to improve the API by:
- Making `submissionMaxSize` generic at the component/package boundary
- Restoring the single `submit` event emit, implicitly branching the payload type so it's chunked if `submissionMaxSize` is non-nullish, monolithic otherwise
This change already felt big enough (especially compared to the #289 1-liner), so I didn't want to hold it up to explore …
=> Emit submission payload(s) to host app

.changeset/healthy-jobs-look.md, .changeset/light-mails-appear.md, packages/scenario/src/serialization/ComparableXMLSerialization.ts, packages/scenario/test/submission.test.ts, packages/xforms-engine/src/instance/Root.ts, packages/xforms-engine/src/lib/client-reactivity/submission/createRootSubmissionState.ts, packages/xforms-engine/src/lib/xml-serialization.ts, packages/xforms-engine/src/parse/model/RootAttributeDefinition.ts, packages/xforms-engine/src/parse/model/RootDefinition.ts, packages/xforms-engine/src/parse/model/RootNamespaceDeclaration.ts, packages/xforms-engine/src/parse/model/RootNamespaceDeclarations.ts
Closes #286.
- Added tests for attributes
- Updated tests for XML namespace declarations
It'd be better to have a more general solution for both attributes and namespace declarations.
Both would involve significant work on both parsing (to capture attributes and namespace prefixes/declarations throughout the primary instance subtree), as well as the primary instance state data model (as we don't have a concept of attributes, and presently ignore non-default-namespace element names).
I'd be remiss if I failed to mention that there would have been an even hacker way to deal with namespace declarations: abuse built-in DOM serialization (as it functionally does the same thing to derive namespaces as this change does more explicitly). I didn't do this because:
- It'd be **a lot less clear** …
=> Include primary instance root attributes, namespace declarations in submission XML

.changeset/funny-items-know.md, .changeset/funny-items-know2.md, .changeset/wise-dancers-itch.md, packages/common/src/fixtures/xpath-fns/variadic-distance.xml, packages/scenario/test/data-types/geo.test.ts, packages/scenario/test/xpath/functions/distance.test.ts, packages/xpath/src/error/JRCompatibleError.ts, packages/xpath/src/error/JRCompatibleGeoValueError.ts, packages/xpath/src/evaluator/functions/FunctionImplementation.ts, packages/xpath/src/functions/xforms/geo.ts, packages/xpath/src/lib/geo/EncodeGeoValueStubError.ts, packages/xpath/src/lib/geo/GeoValueCodec.ts, packages/xpath/src/lib/geo/Geopoint.ts, packages/xpath/src/lib/geo/Geotrace.ts, packages/xpath/src/lib/geo/GeotraceLine.ts, packages/xpath/src/lib/geo/encodeGeoValueStubFactory.ts, packages/xpath/src/lib/geo/geopointCodec.ts, packages/xpath/test/xforms/geo.test.ts
Closes #118. Supersedes and closes #244.
**Please don't pay too much attention to the commit history of this branch!** It's... well, it's bananas.
I expect we'll want to squash this on merge.
I don't **think** there should be anything browser specific that wouldn't be caught by CI running tests across targeted browsers. Happy to manually verify if we feel otherwise in review!
- Incorporated test coverage from getodk/javarosa#761
- Added a test to clarify multi-argument type semantics
- Updated `@getodk/xpath` tests where appropriate
- Updated previously failing scenario tests to reflect related improvements
This expands on the _logical changes_ in #244 with:
- a minor semantic correction, for the distinction between single-argument and variadic calls
- an incremental effort to isolate …
=> Variadic `distance`, minor related XPath geo functionality improvements

packages/common/src/fixtures/preview-service/xforms/cities.geojson
~~Closes #~~
Ran `yarn workspace @getodk/web-forms dev`, no longer see error loading the "all questions" demo form.
This file wasn't included when we introduced the demo form, but we didn't yet support external secondary instances so it didn't matter much.
I haven't added any of the _other media_ resources referenced by the form here. I'm hoping that, with whatever design we end up with for supporting those other form attachments, we'll similarly be alerted that they're absent. If nothing else, I think that will be an opportunity to make sure the form itself is up to date as well.
N/A
This is adding a resource which was missing for the "all questions" form.
See above.
=> Add `cities.geojson`, external secondary instance for “all questions" demo form

.github/workflows/release.yml, README.md, packages/scenario/package.json, packages/tree-sitter-xpath/package.json, packages/web-forms/package.json, packages/xforms-engine/package.json, packages/xpath/package.json
Closes #
Nothing! Unfortunately I think we just have to try this one.
I considered automating more but I think this is a good balance of keeping a human in the loop and automating the tedious. We'll still do a PR to generate and verify the changelogs. Then once that gets merged we'll push tags and that will trigger automatic publish. We can add more automation later if we want.
Should have no effect other than incentivizing us to release more!
=> Automate release

.github/workflows/release.yml
After pushing a tag in the last commit `@0.7.0` (already removed) the job was triggered but skipped: 
I believe it's because of the IF condition. 
- Removes IF condition in publish workflow
=> chore: removes IF condition in the publish workflow

.github/workflows/release.yml
`*` in Github's glob-like matching matches patterns without '/': https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
=> Match patterns including /

.changeset/lemon-pumpkins-smile.md, .changeset/silly-candles-battle.md, packages/web-forms/src/components/OdkWebForm.vue, packages/web-forms/src/index.ts, packages/web-forms/src/lib/constants/control-flow.ts, packages/web-forms/src/lib/init/FormState.ts, packages/web-forms/src/lib/init/engine-config.ts, packages/web-forms/src/lib/init/initializeFormState.ts, packages/web-forms/src/lib/init/loadFormState.ts, packages/web-forms/src/lib/init/updateSubmittedFormState.ts, packages/web-forms/src/lib/submission/HostSubmissionResultCallback.ts, packages/web-forms/tests/components/OdkWebForm.test.ts
All of #247 except UI/UX revisions!
I have verified this with tests. We'd need to simulate a host app integration to verify it in browsers. I still don't think anything here would be browser specific.
Testing:
- A quick validation that loading a form with `editInstance` input results in a form with that instance's state
- Much more validation that the solution for creating multiple instances doesn't introduce regressions (i.e. "everything is optional")
Some of this involved cleaning up the states possible in `OdkWebForm` (currently the primary host app interface). It wasn't strictly necessary, but the necessary features required additive changes to possible state which I found **really hard** to reason about without making it more explicit.
As best as I could, I exercised the regression …
=> Initial support for editing submissions, resetting form state after submission

.github/workflows/ci.yml, packages/xpath/test/helpers.ts, packages/xpath/test/setup.ts, packages/xpath/test/xforms/now.test.ts, packages/xpath/vite.config.ts
Closes https://github.com/getodk/web-forms/issues/324
**To reproduce the error:** 
1. Change the machine time to March 1st at 23:30 Los Angeles timezone
2. Run the test suite `yarn workspace @getodk/xpath test`
3. See the tests failing like this:
**Other things done:**
After implementing the fix, I tried setting my machine in different timezones, ran the tests, and they passed. The different timezones have been passed to the ["now" function correctly](https://github.com/getodk/web-forms/blob/99295eb1d6ec78cd6a758385793e97859b6a74cc/packages/xpath/src/lib/datetime/functions.ts#L24). 
The offset is being appended to the [localDateTimeString](https://github.com/getodk/web-forms/blob/99295eb1d6ec78cd6a758385793e97859b6a74cc/packages/xpath/src/lib/datetime/functions.ts#L14)
I tried making a …
=> fix(#324): runs xpath tests with the same timezone

.github/workflows/ci.yml
Fixes failure to produce a build artifact on merge to `main`. (Or at least, I think it fixes that!)
Closes # (do we have an issue for this?)
After the first failed attempt in #368, I did a bunch of trial and error in a private personal repo. Note: I haven't validated the fork-specific logic (because no fork of private personal repo)! But I have validated that jobs predicated on that condition run as expected (and don't run for a negative predicate result).
It probably isn't the best possible solution!
- I briefly considered investigating other CI solutions but we don't want that.
- We discussed making the build -> upload artifact job more explicit. I think we should do that but don't want to block a pragmatic fix over it.
I could imagine a few hundred ways this breaks assumptions we have …
=> Skip CI if-and-only-if run from a non-fork PR

.changeset/icy-llamas-fail.md, packages/web-forms/src/components/controls/Input/InputText.vue
Closes #301
<details><summary>Happy path and required state</summary>
https://github.com/user-attachments/assets/8e4f2783-0b2b-4661-8ffb-1d1c42c9bc6a
</details>
<details><summary>Disabled state</summary>
</details>
<details><summary>Firefox & Safari Desktop</summary>
</details>
Needs testing in mobile
- Adds Text Area input that is displayed if `rows` has a value greater than zero
- Multiline appearance will be done later
=> feat(#301): Add support for a multiline text question type.

.changeset/icy-llamas-fail.md, README.md, feature-matrix.json, packages/web-forms/CHANGELOG.md, packages/web-forms/package.json
Prepares release
I added the `rows` parameter and in doing so noticed that the `label` and `value` parameters were marked as incomplete. I verified that they are fully supported with the following form: 
[external-data(1).csv](https://github.com/user-attachments/files/20197341/external-data.1.csv)
[select-one-file(1).xlsx](https://github.com/user-attachments/files/20197342/select-one-file.1.xlsx)
=> Prepare release with support for rows attribute on text

.changeset/fifty-plums-live.md, README.md, feature-matrix.json, packages/web-forms/src/assets/css/reset.scss, packages/web-forms/src/components/FormHeader.vue, packages/web-forms/src/components/FormLanguageMenu.vue, packages/web-forms/src/components/OdkWebForm.vue
Closes #412
Tested in Central, Blank project, and Preview page
<details><summary>Resizes "Powered by"</summary>
</details>
<details><summary>Language dropdown in Central</summary>
https://github.com/user-attachments/assets/1019d043-8132-4870-a650-5894e406e9e5
</details>
<details><summary>Language dropdown - desktop, mobile</summary>
</details>
Simplifies user experience
They cannot print the form, but that's fine; we will observe user feedback and evaluate if it adds value.  
No
- Removes print button
- Resizes "Powered by" based on Yaw and Aly's feedback
- Removes hamburger menu and uses dropdown language in mobile view
=> feat(#412): removes print button

.changeset/puny-peaches-listen.md, packages/web-forms/src/components/widgets/MultiselectDropdown.vue, packages/web-forms/src/components/widgets/SearchableDropdown.vue
Closes #422
Test video:
https://github.com/user-attachments/assets/8746e975-5478-4d6e-a2e9-a357e3c3cd6d
- Proper use of select's filter. The label can't be a function; it breaks the filter. 
- Search now filters by label
- Process label when getting options 
- Search is by `contains` and case-insensitive
=> fix(#422): select's search filters by label

.changeset/green-coins-change.md, packages/web-forms/src/components/controls/RankControl.vue
Closes #413
Manual testing - video: 
https://github.com/user-attachments/assets/44b05a2a-f25e-48f4-8f11-8552146d82d4
Reuses existing code
- Better visual feedback of the option's new position in the list 
- Doubles the time of the highlight effect after an option is moved to a new position 
- Adds the highlight effect after an option is dragged to a new position
=> chore(#413): improves rank's visual highlight

packages/web-forms/src/assets/css/style.scss
Possible fix for #438.
---
See https://sass-lang.com/documentation/breaking-changes/import/
Closes #438
No other options considered.
No effect.
No.
replaced deprecated global map-get with map.get
=> web-forms/sass: replace deprecated global map-get with map.get

.changeset/stupid-clocks-spend.md, packages/web-forms/src/components/FormLoadFailureDialog.vue, packages/xforms-engine/src/error/LoadFormFailureError.ts
Closes #390
Before the improvements:
- Printing a long message in red
- Hard to scroll to the technical details
https://github.com/user-attachments/assets/51d3a768-79d8-4dce-81ad-d2810252a695
Video showing the new user experience: 
- Moves technical details to a collapsible section, keeping the message for the user simple.
- The dialog is less wide
- The font isn't bold
https://github.com/user-attachments/assets/a4fc8d8a-02a4-4db4-b1d1-3ce048778491
- Updated dialog styles as per [designer notes](https://getodk.slack.com/archives/C051L6AKG4F/p1752011473893869). 
- Removed the raw data from the message, which was printing the entire XML, resulting in a lengthy wall of red text.
- Moved the error message to the technical section and part of the stack info.
=> feat(#390): Improves error dialog style and message

packages/web-forms/src/components/FormLoadFailureDialog.vue, packages/web-forms/src/components/common/GeopointFormattedValue.vue
<details><summary>Dialogs showing correct UI and sizes:</summary>
<br />
</details>
<details><summary>Geopoint's readonly value is the same as other notes:</summary>
<br />
</details>
- Scope CSS to error dialog
- Make Geopoint's readonly value style consistent with other question types
=> fix: CSS for dialogs and Geopoint's readonly value

.github/workflows/ci.yml
The CI was initially set up to trigger on both `push` and `pull_request` events. Later, to streamline things and avoid duplicate runs, we decided to limit `push` triggers to commits merged into `main` and keep `pull_request` triggers for PRs only. However, PRs from forks weren’t triggering the CI at all, and this PR fixes that issue.
- Fixes condition to detect forks
=> fix: enable CI for pull requests from forked repositories

.changeset/khaki-plants-fix.md, packages/web-forms/src/components/appearances/FieldListTable.vue, packages/web-forms/src/components/common/CheckboxWidget.vue, packages/web-forms/src/components/common/RadioButton.vue
Closes #460
Test video:
https://github.com/user-attachments/assets/90fa491b-8769-4a9f-bfef-a2d57f41da97
- Labels (the first column in each row) use 35% and options evenly divide up the rest on a wide screen for both Desktop and Mobile
- Prevents selecting options when `label` appearance is present
=> fix(#460): long labels in list table

.changeset/witty-boxes-serve.md, packages/scenario/test/instance-attachments/binary-output.test.ts
=> test(#475): fix unreliable test based on random number generation

.changeset/real-peas-hear.md, README.md, feature-matrix.json, packages/common/src/jr-resources/JRResourceURL.ts, packages/scenario/test/message-output.test.ts, packages/scenario/test/repeat-output.test.ts, packages/xforms-engine/src/client/TextRange.ts, packages/xforms-engine/src/lib/reactivity/text/createTextRange.ts, packages/xforms-engine/src/parse/body/control/ItemsetDefinition.ts, packages/xforms-engine/src/parse/expression/BindComputationExpression.ts, packages/xforms-engine/src/parse/expression/ItemsetNodesetExpression.ts, packages/xforms-engine/src/parse/expression/ItemsetValueExpression.ts, packages/xforms-engine/src/parse/expression/RepeatCountControlExpression.ts, packages/xforms-engine/src/parse/expression/TextChunkExpression.ts, packages/xforms-engine/src/parse/expression/abstract/DependentExpression.ts, packages/xforms-engine/src/parse/model/ItextTranslationsChunks.ts, packages/xforms-engine/src/parse/model/ModelDefinition.ts, packages/xforms-engine/src/parse/model/generateItextChunks.ts, packages/xforms-engine/src/parse/text/ItemsetLabelDefinition.ts, packages/xforms-engine/src/parse/text/MessageDefinition.ts, packages/xforms-engine/src/parse/text/abstract/TextElementDefinition.ts, packages/xforms-engine/src/parse/text/abstract/TextRangeDefinition.ts, packages/xforms-engine/src/parse/xpath/semantic-analysis.ts
Closes: #22
Closes: #418
- Scenario enabled
- Performance profiled and found to be an improvement when switching languages, and comparable for other cases
1. During reactive evaluation. This was complex and meant rework was being done reactively.
2. During parsing of the form. This worked well and was idiomatic but couldn't handle more complex cases like itemsets where the itext key had to be computed at runtime.
3. During xpath eval but this was expensive and not idiomatic.
4. Evaluating the itext elements outside of context (this PR). This is idiomatic and works in all cases I found and improves the complexity of the code. There is a risk of doing more work than necessary as it evaluates for languages that may never be selected, but performance profiling showed it to be acceptable.
More …
=> feat(#22): support output in translation text

.changeset/shy-carpets-add.md, packages/scenario/test/choice-name.test.ts, packages/xpath/src/functions/javarosa/select.ts
New tests added to catch the error.
As far as I can tell this situation indicates a form that can never be valid, so failing loudly and early is preferable to find the issue ASAP. 
Discussion: https://github.com/getodk/web-forms/pull/496#discussion_r2377274153
Instead of invalid forms swallowing the error, it will now be thrown.
=> fix(#117): throw an error when called with a ref that does not exist
